# Generated by Django 4.1.2 on 2022-11-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['date_add']},
        ),
    ]
